services:
  yeppbot:
    container_name: YEPPBot
    image: mcmodersd/yeppbot:1.26.0-PTB-latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "6767:80/tcp" # HTTP
      - "420:420/tcp" # HTTPS
    volumes:
      - ./config.json:/app/config.json
      - ./account.key:/app/account.key
      - ./privkey.pem:/app/privkey.pem
      - ./fullchain.pem:/app/fullchain.pem

networks:
  default:
    name: YEPPBot-Network