<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.MCmoderSD</groupId>
    <artifactId>YEPPBot</artifactId>
    <version>1.26.0-PTB-1</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>Nexus</id>
            <name>Sonatype Nexus</name>
            <url>https://mcmodersd.de/nexus/repository/maven-releases/</url>
        </repository>
    </repositories>

    <dependencies>

        <!-- BDSM-Test-API -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>BDSM-Test-API</artifactId>
            <version>1.0.1</version>
        </dependency>

        <!-- Helix-API -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>Helix-API</artifactId>
            <version>2.3.4</version>
        </dependency>

        <!-- HTTPS-Server -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>HTTPS-Server</artifactId>
            <version>3.1.5</version>
        </dependency>

        <!-- JSON Utility -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>JsonUtility</artifactId>
            <version>1.5.6</version>
        </dependency>

        <!-- JSQL Driver -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>JSQL-Driver</artifactId>
            <version>3.1.2</version>
        </dependency>

        <!-- OpenAI -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>OpenAI</artifactId>
            <version>3.3.8</version>
        </dependency>

        <!-- OpenWeatherMap -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>OpenWeatherMap</artifactId>
            <version>1.2.1</version>
        </dependency>

        <!-- ZIP Tools -->
        <dependency>
            <groupId>de.MCmoderSD</groupId>
            <artifactId>ZIP-Tools</artifactId>
            <version>1.2.0</version>
        </dependency>

        <!-- Twitch4J -->
        <dependency>
            <groupId>com.github.twitch4j</groupId>
            <artifactId>twitch4j</artifactId>
            <version>1.26.0</version>
        </dependency>

        <!-- SLF4J -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.18</version>
        </dependency>

        <!-- XxHash -->
        <dependency>
            <groupId>at.yawk.lz4</groupId>
            <artifactId>lz4-java</artifactId>
            <version>1.11.0</version>
        </dependency>

        <!-- Jackson Databind -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.22.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>shade</goal></goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <shadedArtifactAttached>true</shadedArtifactAttached>

                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>config/</exclude>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>

                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>de.MCmoderSD.main.Main</mainClass>
                                    <manifestEntries>
                                        <Multi-Release>true</Multi-Release>
                                    </manifestEntries>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>

                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>