name: Publish Docker image for Dev-Branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types:
      - closed
  workflow_dispatch: # Allows triggering manually from GitHub UI

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to harbor
        id: docker_build_push
        run: |
            docker build ./ -t mcmodersd/yeppbot:${{ github.run_number }}.${{ github.run_attempt }} -t mcmodersd/yeppbot:dev
            docker push mcmodersd/yeppbot --all-tags